# Generated by Django 3.0.2 on 2020-02-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200224_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial',
            name='clases',
            field=models.TextField(help_text='Para conocer los iconos, entrar a https://ionicons.com/'),
        ),
    ]
