# Generated by Django 3.0.2 on 2020-02-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200224_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='redsocial',
            name='icons_folder',
            field=models.TextField(default='/static/blog/ionicons', editable=False),
        ),
    ]
