# Generated by Django 3.0.2 on 2020-02-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_redsocial_icons_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redsocial',
            name='clases',
            field=models.TextField(help_text='Para conocer los iconos, entrar a https://ionicons.com/, NOTA: SOLO UTILIZAR ICONOS FILLED'),
        ),
    ]
