# Generated by Django 3.0.2 on 2020-02-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200224_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlace',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enlace',
            name='icons_folder',
            field=models.TextField(default='/static/blog/ionicons', editable=False),
        ),
        migrations.AlterField(
            model_name='enlace',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='RedSocial',
        ),
    ]
