# Generated by Django 3.0.2 on 2020-02-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_enlace_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlace',
            name='grosor',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enlace',
            name='tipo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
