# Generated by Django 3.0.2 on 2020-02-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200224_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_experiencia', models.IntegerField()),
                ('nombre_institucion', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, help_text='Dejar en blanco si aún estás trabajando', null=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('activo', models.BooleanField(default=True, verbose_name='Mostrar?')),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Experiencias',
            },
        ),
        migrations.AddField(
            model_name='configuracionbasica',
            name='fecha_nacimiento',
            field=models.DateField(default='1992-09-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracionbasica',
            name='hobbies',
            field=models.CharField(default='asdf', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracionbasica',
            name='nombre_completo',
            field=models.CharField(default='Patricio Adán Muñoz Roa', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracionbasica',
            name='run',
            field=models.CharField(default='18.069.609-1', help_text='Formato sugerido XX.XXX.XXX-X, no está validado, así que depende de tí', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracionbasica',
            name='descripcion_general',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='configuracionbasica',
            name='numero_contacto',
            field=models.CharField(help_text='No añadir el +569', max_length=8),
        ),
    ]
