# Generated by Django 3.0.2 on 2020-02-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200225_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
