# Generated by Django 3.0.2 on 2020-02-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200225_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='nombre_cargo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
