# Generated by Django 3.0.2 on 2020-02-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_curriculum_nombre_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='nombre_cargo',
            field=models.CharField(help_text='Cargo, Carrera, Curso o Tipo de enseñanza', max_length=50),
        ),
    ]
