# Generated by Django 3.0.2 on 2020-02-27 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200225_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaExperiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_experiencia', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CategoriaExperiencia',
                'verbose_name_plural': 'CategoriasExperiencias',
            },
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='tipo_experiencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.CategoriaExperiencia'),
        ),
    ]
