# Generated by Django 3.0.3 on 2020-02-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_contacto_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
    ]
