# Generated by Django 3.0.3 on 2020-02-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_contacto_respondido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria Post', 'verbose_name_plural': 'Categorias Posts'},
        ),
        migrations.AlterModelOptions(
            name='categoriaexperiencia',
            options={'verbose_name': 'Categoria Curriculum', 'verbose_name_plural': 'Categorias Curriculum'},
        ),
        migrations.AlterModelOptions(
            name='configuracionbasica',
            options={'verbose_name': 'Configuración Básica', 'verbose_name_plural': 'Configuraciones Básicas'},
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name': 'Experiencia Curriculum', 'verbose_name_plural': 'Experiencias Curriculum'},
        ),
        migrations.AlterModelOptions(
            name='enlace',
            options={'verbose_name': 'Redes Sociales', 'verbose_name_plural': 'Redes Sociales'},
        ),
        migrations.AlterField(
            model_name='enlace',
            name='link',
            field=models.URLField(help_text='Poner ruta completa, ejemplo https://www.facebook.com/<username>/'),
        ),
    ]
