# Generated by Django 3.0.3 on 2020-02-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200227_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionbasica',
            name='share_this',
            field=models.URLField(blank=True, help_text='https://sharethis.com/onboarding/', null=True),
        ),
    ]
