# Generated by Django 3.0.3 on 2020-02-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_banner', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(help_text='Link al portal de donación')),
                ('titulo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Banners',
                'verbose_name_plural': 'Banners',
            },
        ),
    ]
