# Generated by Django 3.0.3 on 2020-02-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
