# Generated by Django 3.0.3 on 2020-02-29 03:18

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0021_banners_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionbasica',
            name='apodo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='configuracionbasica',
            name='descripcion_corta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='configuracionbasica',
            name='descripcion_general',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='configuracionbasica',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='configuracionbasica',
            name='hobbies',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
